### ISSUE TITLE
openbox+tint2: does not start minimized to tray

### ISSUE THREAD

**Issue by Vladar4** [marazmista/radeon-profile#107]
Arch + openbox 3.6.1 + tint2 16.6.1.

Program starts as a window minimized to a panel, not hidden into its tray icon.

The required config options are checked:
* Start minimized
* Minimize to tray
* On close hide to tray
* Save window geometry

The issue looks similar to this closed one: https://github.com/marazmista/radeon-profile/issues/23

**Comment by eversins** [comment]
Same issue on Manjaro KDE.

**Comment by marazmista** [comment]
Should be fixed with commit 19de258c4bddb220c02989c8134a51c830865240

**Comment by Vladar4** [comment]
Tried and it seems to be working.

**Comment by marazmista** [comment]
Thanks for confirmation.
