### ISSUE TITLE
Graphs are always black

### ISSUE THREAD

**Issue by Zamundaaa** [marazmista/radeon-profile#108]
As the title says.
Also I can't set the performance level, it stays stuck on Performance, if I try setting it to battery or balanced it switches back in a fraction of a second. Could it have something to do with me having a RX 580 Sapphire Nitro+ that has a hardware switch for performance level (albeit just 2 possible states)?

**Comment by marazmista** [comment]
Not sure what you mean, could you provide screenshot of this black graphs?
About changing states, it seems that writing value to sysfs failed, do you have daemon installed?

**Comment by Zamundaaa** [comment]
Here's the screenshot of black graphs. I have no idea which is which.
![screenshot_20190211_124459](https://user-images.githubusercontent.com/20477130/52561341-64a3ac00-2dfb-11e9-8241-288f3a316b5c.png)
I do have the deamon installed with the AUR package and I'm sure it's running
![screenshot_20190211_124826](https://user-images.githubusercontent.com/20477130/52561357-77b67c00-2dfb-11e9-8cc0-86742059378f.png)
I don't know if that could point to the issue but there seems to be some file path empty or something
![screenshot_20190211_131642](https://user-images.githubusercontent.com/20477130/52562624-5eafca00-2dff-11e9-9fe3-093074e82032.png)

**Comment by parkerlreed** [comment]
Have you set a color? Default is black. It doesn't auto pick colors

![image](https://user-images.githubusercontent.com/841440/52578517-5b621180-2df2-11e9-95ba-a0112c313004.png)

**Comment by Zamundaaa** [comment]
Ah yes. I feel a little stupid now...
Should I open a seperate issue about power states not being set? The whole Overclock tab doesn't work for me either. No clockspeed setting and the "States Table" sub-tab is greyed out

**Comment by parkerlreed** [comment]
@Zamundaaa Yeah separate issue if one doesn't already exist.

**Comment by Zamundaaa** [comment]
Ok the rest of the issues is now tracked on #120
