### ISSUE TITLE
Fan percentage and fan rpm shown wrong for RX Vega 56

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [marazmista/radeon-profile#115]
The shown fan rpm and fan percentage is completly wrong. When the fans are at 1000rpm, it shows 50 - 60 rpm. This seems not to be an amdgpu specific issue as i use an gnome shell extension which shows the correct rpm values. I use the following gnome shell extension:

https://extensions.gnome.org/extension/1460/vitals/

I hope the code of this extension could help fixing the bug

System: Manjaro Linux, Kernel 4.20, Mesa 18.3.2, Radeon RX Vega 56.

![wrong-rpm](https://user-images.githubusercontent.com/41188546/52232975-30d9fb00-28be-11e9-9122-2b6d05c94476.png)

**Comment by fatino** [comment]
I have the same issue with RX 470. Percentage seems to be correct. Just the RPM number seems wierd.

**Comment by aaulia** [comment]
+1, RX 470, same issue.

**Comment by marazmista** [comment]
probably fixed in commit c29341c3a363a9fb14a64865f685966f083f97f7

**Comment by Sebastian-Hirsch** [comment]
It works for me now. I will close the issue.
