### ISSUE TITLE
Overheat after switching user

### ISSUE THREAD

**Issue by carg0cult** [marazmista/radeon-profile#121]
Radeon profile was running for one user. Then another user logged in and used a 3d heavy game. That user did not start radeon profile. The fan did not spin up. Switching back to the first user made the fan spin up and it showed the GPU was extremely hot. 
I don't like the philosophy of fan control being a per-user setting. But if it is, some sensible default fan speed should be applied in a scenario like above to prevent overheating.

**Comment by marazmista** [comment]
It is not per-user but rather system wide. When one user change some settings in sysfs all users are affected.
Looks like after switching the user, connection to daemon is still active but gui is frozen. I commuted the changes to daemon and radeon-profile to check connection periodically and if daemon won't get response from radeon-profile, it restores fan control to default, auto state.
