### ISSUE TITLE
Poor performance after undervolting & pstate changes doesn't stick after restart.

### ISSUE THREAD

**Issue by aaulia** [marazmista/radeon-profile#122]
My system information

```
~ 
➜ uname -a && pacman -Q radeon-profile-git radeon-profile-daemon-git && inxi -G 
Linux archbox 4.20.8-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 13 00:06:58 UTC 2019 x86_64 GNU/Linux
radeon-profile-git 20190211.r0.g52f3ee3-1
radeon-profile-daemon-git 20190124.r6.g05bdb90-1
Graphics:  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X] driver: amdgpu v: kernel 
           Display: tty server: X.Org 1.20.3 driver: amdgpu resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD Radeon RX 470 Graphics (POLARIS10 DRM 3.27.0 4.20.8-arch1-1-ARCH 
           LLVM 7.0.1) 
           v: 4.5 Mesa 18.3.3 
```

I've tried and succeed in manually setting the p-state voltage for 6th and 7th state through amdgpu's `sysfs`

Every time I tried changing the voltage from `radeon-profile` it always result in poor performance in games or benchmark that I did after (ie. what usually run around 60 fps are now run in 15 fps). Also after restarting the computer, all settings are back to normal.

**Comment by marazmista** [comment]
After changing values from radeon-profile, could you check the file manually to see if they were applied?

**Comment by aaulia** [comment]
This is the status of the `sysfs` p-state table before and after I apply the changes from `radeon-profile`. It seems that it's doing it correctly.  

![voltage_status](https://user-images.githubusercontent.com/161797/52907601-3ad50400-3297-11e9-9b5c-4a87c87bdc13.png)  
  
One suspicious thing that I notice is how the power cap is at `0w`?  

![radeon_profile_states_tbl](https://user-images.githubusercontent.com/161797/52907602-3dcff480-3297-11e9-955d-79afe04203c3.png)  

This is my gpu status during a benchmark, notice how the gpu clock speed seems to stuck at `300MHz` and voltage is at `1000mV`.  

![gpu_status_during_benchmark](https://user-images.githubusercontent.com/161797/52907658-44ab3700-3298-11e9-8700-82cf284b8c2b.png)

Lastly this is my `power1_cap` status, it show normal `130w` default power cap, AFAIK
```
~ 
➜ cat /sys/class/drm/card0/device/hwmon/hwmon0/power1_cap    
130000000
```

**Comment by aaulia** [comment]
Hello, I have more information. After reading [archwiki](https://wiki.archlinux.org/index.php/AMDGPU#Overclocking) entry on overclocking. I decided to check on the p-state's state. It seems that after setting the voltage (or maybe anything that related to the p-states) it's stuck/locked on the first state.  

![stuck_p_state](https://user-images.githubusercontent.com/161797/52915181-537b0380-3303-11e9-86b9-3ebd129451bc.png)

**Comment by Sebastian-Hirsch** [comment]
I can confirm the power cap issue with my RX Vega 56. It is at 0 watts even though it should be at 247W (the value i have set with my own oc script). The max value of the slider is erratically at 99W, which is wrong too.

**Comment by marazmista** [comment]
Commit e089053a3f1f8f906424263ed61d585f4eb6964c should fix power cap issue.
Saving pstates adjustments, this on the todo here: https://github.com/marazmista/radeon-profile/projects/1#card-16937033

What if you try to enable other states after adjusting values? Following archwiki it should look like this: `echo "0 1 2 3 4 5 6 7" >  /sys/class/drm/card0/device/pp_dpm_sclk`
It is interesting that the states got stuck after pstate table modifications. I don't quite understand the relation between some files. For example, I'm not sure if percent overclock via `pp_sclk_od` can be applied in the same time as `pp_od_clk_voltage` adjustments.

**Comment by Sebastian-Hirsch** [comment]
I can confirm, that the correct power target is now shown correctly.
For the percentage overclocking issue I would suggest to just drop it for all cards, as the state table method is all around better. There could indeed a problem using both but I am not knowledgeable enough in this regard. I would by default just enable the state table overclocking for all cards that support it and the percentage oc for older cards that not support state tables. A list with supported cards for state table oc would be helpful here.

**Comment by aaulia** [comment]
The latest commit(s) actually fix the problem. The GPU clock correctly goes to `1260MHz` and the voltage to `1025mV`. The last problem I guess is that the configuration doesn't survive reboot. Because after rebooting the values goes back to default.  

One minor UI problem, the p-state graph only show changed states instead of the whole states, after modification.

![2019-02-19-112101_835x680_scrot](https://user-images.githubusercontent.com/161797/52990019-b326fb00-3438-11e9-80c2-8c41c8ab6681.png)

**Comment by marazmista** [comment]
Plot issue fixed 4b10fe23e5ed8d45da31fe31954784be20d380a7
Reboots will always reset values, even after I implement saving pstates adjustments, you will need to launch radeon-profile to apply modified numbers.

**Comment by aaulia** [comment]
Nope, it doesn't save p-state configurations after reboot.

![radeon_profile_after_reboot](https://user-images.githubusercontent.com/161797/53058287-11111c80-34e5-11e9-9ee9-169f41c823d0.png)  

![terminal_clock_daemon_after_reboot](https://user-images.githubusercontent.com/161797/53058292-12dae000-34e5-11e9-9a1f-6f2705fe9e54.png)  

In comparison, the fan control configurations survive reboot, and being (re-)applied every time.

**Comment by aaulia** [comment]
> Plot issue fixed [4b10fe2](https://github.com/marazmista/radeon-profile/commit/4b10fe23e5ed8d45da31fe31954784be20d380a7)
> Reboots will always reset values, even after I implement saving pstates adjustments, you will need to launch radeon-profile to apply modified numbers.

Just to be clear, maybe I'm mistaken with my assumption. So I have to re-input my voltages and hit apply every time I reboot my PC? Because I'm under the impression that it would work just like the fan control config.

**Comment by marazmista** [comment]
I assume you have radeon-profile in autostart.
> So I have to re-input my voltages and hit apply every time I reboot my PC?

Correct. Restoring modified values at application startup (like fan profiles) is not implemented yet.

**Comment by aaulia** [comment]
Great, so I can close this issue then. Thank you
