### ISSUE TITLE
Tray icon tooltip displays incorrect information and does not refresh

### ISSUE THREAD

**Issue by siyia2** [marazmista/radeon-profile#127]
Hello hovering over the radeon-profile tray icon does not display correct gpu info, nor does it refresh the info.This happens only if i minimize the program  or close to tray icon

**Comment by siyia2** [comment]
Tray tooltip only refreshes gpu info if i have radeon-profile window open on GPU Summary

**Comment by marazmista** [comment]
Fixed: 39b23b54153918fd28dbd094fa73ec1ea3a338ab

**Comment by siyia2** [comment]
thx that did it!!!amzing efforts from you and a greate program to have for amd/radeon users!
