### ISSUE TITLE
Light gpu load not being reported

### ISSUE THREAD

**Issue by siyia2** [marazmista/radeon-profile#128]
Hello, gpu load when playing light games or videos and youtube is reported as 0%, running furmark gpu load shows at 100% as it should.

Kernel: 4.19.20
Driver: Mesa 18.3.4
GPU: RX 550
OS: Debian 10

**Comment by siyia2** [comment]
i checked with "watch cat /sys/class/drm/card0/device/gpu_busy_percent" and the gpu load behavior matches the radeon-profile behavior maybe it is a kernel-mesa issue

**Comment by marazmista** [comment]
Hi, there is info about gpu load also in `amdgppu_pm_info` file in debugfs, but apparently the source of this value is the same as `gpu_busy_percent`. radeon-profile doesn't do any calculations here, just reads value. Here is some info: https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/1031816-amdgpu-drm-driver-to-finally-expose-gpu-load-via-sysfs
