### ISSUE TITLE
Plot renaming does not work properly

### ISSUE THREAD

**Issue by kfilippop** [marazmista/radeon-profile#130]
I realised that a properly set up plot had wrong name. Clicked modify, changed name, saved. In the plot list the profile with the wrong name was still there. Repeated the procedure a second time, still no change. When I clicked apply to see the plot there appeared three identical plots ie the misnamed+myattempt#1+myattempt#2 only the last two were "invisible" in the plot list.

**Comment by marazmista** [comment]
Fixed in commit 8e5ef9f013d73a39346cc739827691e8a8fcb843
