### ISSUE TITLE
radeon-profile has greyed out options and I don't know what else to try

### ISSUE THREAD

**Issue by RavenChan1023** [marazmista/radeon-profile#131]
As the title states, on radeon-profile, the overclock option is greyed out even after running with sudo, along with most other options relating to it and I don't know what's going wrong. Some people have said it may not work with amdgpu or something, but either way, I have a screenshot. Performance is absolutely abysmall, I really need this overclock but I will not modify the linux kernel in any way as that seems to be the only other option I can find. Clicking "change profile" just automatically reverts it back to "auto." Using integrated graphics since my dedicated nvidia gpu is pretty close to dying permanently.
![radeonocgrey](https://user-images.githubusercontent.com/37986598/55685506-ae50d480-591c-11e9-9da9-3474434963f3.png)

**Comment by parkerlreed** [comment]
You have to enable the feature mask for overclocking. 

https://wiki.archlinux.org/index.php/AMDGPU#Overclocking

Add that ppfeaturemask parameter to your kernel command line (in whichever bootloader you use)

**Comment by marazmista** [comment]
Looks like your card is too old for `amdgpu` to work:
https://en.wikipedia.org/wiki/AMD_700_chipset_series#760G
