### ISSUE TITLE
Topbar configuration max height

### ISSUE THREAD

**Issue by Jayrgo** [marazmista/radeon-profile#136]
the maximum height of the topbar config dialog is too small
when i maximize the window i still have a vertical scrollbar

please increase the maximum height of this dialog

initial window size:
![Screenshot_2019-06-05_21-57-47](https://user-images.githubusercontent.com/13069032/58986470-ba062d80-87dd-11e9-9599-148ec53fb717.png)

maximized:
![Screenshot_2019-06-05_21-57-58](https://user-images.githubusercontent.com/13069032/58986309-6c89c080-87dd-11e9-8176-9aae45040190.png)

**Comment by marazmista** [comment]
Fixed: 88cc748a11b481153a9abca7561aa57e4b98ac0f

**Comment by Jayrgo** [comment]
thank you
