### ISSUE TITLE
Manually choosing a memory clock to eliminate flicking

### ISSUE THREAD

**Issue by TeenCorn** [marazmista/radeon-profile#137]
Allow the user to be able to choose a fixed memory clock. Setting **pp_dpm_mclk** to "2" completely removes the flickering that happens when I set the OverDrive bit on amdgpu.ppfeaturemask. Currently have to open a terminal and run a script to that for me :(

**Comment by marazmista** [comment]
Yes, but first I have to modify UI for this feature because apparently, that file accepts multiple values (to enable/disable states) so list with checkboxes will fit better than current sliders (which allow only one state to be enabled)

**Comment by TeenCorn** [comment]
Nice. Looking forward to the change. And thanks for the handy tool!

**Comment by marazmista** [comment]
Implemented in 9a364be47b751165504362b49b38d011c6712636
