### ISSUE TITLE
Could you add current power usage?

### ISSUE THREAD

**Issue by D33M0N** [marazmista/radeon-profile#140]
It does show only "Power cap", but not the current used power, which I can see in sensors.

amdgpu-pci-1e00
Adapter: PCI adapter
vddgfx:       +0.92 V
fan1:         676 RPM  (min =  400 RPM, max = 4900 RPM)
temp1:        +57.0°C  (crit = +89.0°C, hyst = -273.1°C)
power1:       18.00 W  (cap = 220.00 W)

**Comment by marazmista** [comment]
Do you know which file in sysfs provide that information?

**Comment by TeenCorn** [comment]
Should be the power1_average file in hwmon

**Comment by wedens** [comment]
`/sys/kernel/debug/dri/0/amdgpu_pm_info` has current power consumption

**Comment by marazmista** [comment]
Added in commit: 77d9c7a9b9a771754609626ebfdeaa9db8cd4de4
