### ISSUE TITLE
Charts are in offset of 20 seconds

### ISSUE THREAD

**Issue by Danysan1** [marazmista/radeon-profile#15]
The 3 real-time graphs are in offset of 20 seconds:

![schermata da 2016-01-19 21-51-48](https://cloud.githubusercontent.com/assets/8406735/12432535/20b9b7f8-befc-11e5-912e-b3156a394e7e.png)

I found the reason, in https://github.com/marazmista/radeon-profile/blob/master/radeon-profile/radeon_profile.cpp#L358 and following lines:
``` c++
ui->plotTemp->xAxis->setRange(ticksCounter+20, rangeX,Qt::AlignRight);
ui->plotColcks->xAxis->setRange(ticksCounter+20,rangeX,Qt::AlignRight);
ui->plotVolts->xAxis->setRange(ticksCounter+20,rangeX,Qt::AlignRight);
```
Removing those `+20` from the lines the graph is ok:

![schermata da 2016-01-19 21-51-13](https://cloud.githubusercontent.com/assets/8406735/12432534/20b17818-befc-11e5-994d-8cf711362e84.png)

Do those `+20` have any reason to stay there?
Otherwise we can delete them.

**Comment by marazmista** [comment]
This is 100% intentional, I wanted this gap on the right. I know that it looks like first screen on max zoom, but one can adjust zoom freely.

**Comment by Danysan1** [comment]
Can we add to the options a toggle for this gap?

**Comment by marazmista** [comment]
Option added.
commit: 8f8e38bed45db3285382a9ee2402639030109d95

**Comment by Danysan1** [comment]
Thank you!
