### ISSUE TITLE
error: ‘PlaceholderText’ is not a member of ‘QPalette’

### ISSUE THREAD

**Issue by Dantali0n** [marazmista/radeon-profile#155]
I can no longer compile from source on Ubuntu 18.04 due to an issue with PlaceholderText not being a member of QPalette.

I am using qt 5.11

**Comment by marazmista** [comment]
Should work after: cfc1fdc920a3d23feba6d7d59d796998e56bcad3

**Comment by Dantali0n** [comment]
Yes, that fixed it. thanks!
