### ISSUE TITLE
Translation of the application. (Closed, decided)

### ISSUE THREAD

**Issue by Ukol1** [marazmista/radeon-profile#160]
Hi marazmista! I decided to translate your program into Russian. The program interface is translated, but the latest help is not included in the translation. When added to the translation code tr() in the uiEvents.cpp after compiling the help is not translated.
The tab is not an active State table, I also translated it.
P.S Sorry for the translation.
`void radeon_profile::on_btn_connConfirmMethodInfo_clicked()
{
    QMessageBox::information(this, tr("Connection confirmation methods info"),
                             tr("0 - (Not recommended in multi user envirnoments) Disable conncection confirmation. Configured options in GUI may get stuck when user session is frozen \n\n" \
                             "1 - (Default) After some time of inactivity when GUI is connected, daemon sends request to GUI to check wheather it is alive. When response is not received it restores fan settings to system default\n\n" \
                             "2 - When no other commands has been sent to daemon, GUI sends periodically alive signals without deamon's requests. Select if you have issues with method 1"));
}` 
![1](https://user-images.githubusercontent.com/30598904/64650056-72301b80-d448-11e9-97d4-f8fc45290e89.png)
![2](https://user-images.githubusercontent.com/30598904/64651081-d6ec7580-d44a-11e9-9753-4bfda1bfa141.png)

**Comment by Ukol1** [comment]
Another conclusion about the diagonal is not properly displayed. I have two monitors, and how many monitors I have is not displayed correctly. What does this icon do, what function does it perform?

![Снимок экрана от 2019-09-11 20-01-23](https://user-images.githubusercontent.com/30598904/64699982-2e80f480-d4d0-11e9-91ec-20bca921e87c.png)

**Comment by marazmista** [comment]
Thanks for translation! I added tr() to that message. (595dcd54445eecf12584e124a93e8abc86729cca)
This refresh button on right updates info in tabs GLX Info, Connectors and Module Info.

**Comment by Ukol1** [comment]
Hi! I added uiEvents.cpp to the file tr(). Only the help title was translated, but the help text remained untranslated. Thanks for the answer! I can you straight for the file translation.

**Comment by Ukol1** [comment]
Me strongly interested in why not active menu State table. I learned during the transfer that there is a power management. I have a video card OK food, long-term load appear distortion or turning off the graphics card. Fan controls don't help.

**Comment by marazmista** [comment]
You can create pull request for translation if you want.
The State table is for overclocking and it is enabled when `pp_od_clk_voltage` file is available in sysfs.

**Comment by Ukol1** [comment]
I do not have such a file in sys... The translation I did for Rosa Linux is included in the package. It is up to you to include the Russian translation in the program. Translation is custom.

**Comment by marazmista** [comment]
I added translation 3a91e0a6df3fece5711dcf46fea67e02bdd03508
Thanks!

**Comment by Ukol1** [comment]
Hello! It’s good that they made a change. I wanted to know how the pp_od_clk_voltage file is created? It turns out that all the program functions do not work for me.

**Comment by Ukol1** [comment]
Hello! Thanks for adding the translation! I will close this topic, we have solved this problem. I’ll open another found more other problems ...
