### ISSUE TITLE
vega64 does not apply memory / core clock 

### ISSUE THREAD

**Issue by MartB** [marazmista/radeon-profile#163]
The memory clock in the states table is not applied to the device, for some reason nothing happens when the memory clocks get changed.

Running the following command manually works though.
`echo "m 3 1050 1000" > "/sys/class/drm/card0/device/pp_od_clk_voltage"`

Core clock changes seem to be broken aswell.

Can someone point me into the right direction?

Edit: installing radeon-profile-daemon and running the app as normal user works.

Running the app standalone using sudo does not work though, interesting.

**Comment by Oxalin** [comment]
Is this still relevent?

**Comment by Benzhaomin** [comment]
Running with sudo radeon-profile still shows

```
QIODevice::write (QLocalSocket): device not open
Failed sending signal:  "2#s 0 852 800#/sys/class/drm/card0/device/pp_od_clk_voltage#2#s 1 991 900#/sys/class/drm/card0/device/pp_od_clk_voltage#2#s 2 1084 950#/sys/class/drm/card0/device/pp_od_clk_voltage#2#s 3 1138 1000#/sys/class/drm/card0/device/pp_od_clk_voltage#2#s 4 1200 1010#/sys/class/drm/card0/device/pp_od_clk_voltage#2#s 5 1401 1010#/sys/class/drm/card0/device/pp_od_clk_voltage#2#s 6 1536 1030#/sys/class/drm/card0/device/pp_od_clk_voltage#2#s 7 1580 1040#/sys/class/drm/card0/device/pp_od_clk_voltage#"
```

**Comment by marazmista** [comment]
@Benzhaomin @MartB
 I pushed a fix in commit 65318da2d39b5e6a153e3d74e6810c4d63de8435. Please try it, I think it should work fine now.

**Comment by Benzhaomin** [comment]
Looks fixed to me, thanks.

**Comment by JoneKone** [comment]
I'm also currently experiencing this issue, I installed a version "Git unstable" (git develop repository) from PPA Ubuntu 20.04 Vega 56, It will change the Power limit, but won't touch pp_od_clk_voltage at all. I tested and CoreControl works fine. You will ask me what version is on, but currently when Corecontrol is running it won't allow me to start Radeon-Profile it is telling me to "At least one core state has to be enabled"

i quest it won't allow me to start it at the same time as CoreCtrl, nor after it was started and stopped. 

On the picture it says v20200824

![Radeon_Vega_State_Table](https://user-images.githubusercontent.com/1114115/91661486-06294600-eae5-11ea-8506-7feefd653de4.jpg)
![Radeon_Profile](https://user-images.githubusercontent.com/1114115/91661488-06c1dc80-eae5-11ea-98a0-46680703211f.jpg)

**Comment by Razer0123** [comment]
Not working for me either

**Comment by Nostromo-KM** [comment]
Fresh install - Manjaro with Cinnamon UI
Kernel 5.4
- Installed from AUR
- Deamon installed from AUR
- Deamon configed to auto-run
- GRUB amdgpu.ppfeaturemask=0xffffffff amdgpu.dpm=1

Created new frequency/voltage states tables but cannot apply them
Tried running sudo - no luck
Tried to do the same with Core-Ctrl - it works.
