### ISSUE TITLE
Navi10 - Its possible to configure frequency lower than 300Mhz?

### ISSUE THREAD

**Issue by EduFrazao** [marazmista/radeon-profile#166]
Hi. I have a RX 5700XT, with this software versions:

Kernel: 5.4.0-rc2
Mesa: 19.2.0
LibDRM: 2.4.99
LLVM: 9.0.0

When setting "low" to Performance Level, GPU clock stays at minimum of 300Mhz. When setting auto, it uses a minimum of 800Mhz. Its possible to use lower values, like Windows driver does?

**Comment by marazmista** [comment]
Hi, I don't think so because there is not much you can do when card control itself while on auto. I guess thos is more to Linux driver.

**Comment by EduFrazao** [comment]
@marazmista thanks for the answer!
