### ISSUE TITLE
Can't compile on Ubuntu 19.10

### ISSUE THREAD

**Issue by bkdwt** [marazmista/radeon-profile#167]
When I try to compile with qmake, this error appears:
```
Project MESSAGE: Building for release
Project ERROR: Unknown module(s) in QT: charts
```

I have checked `/usr/lib/x86_64-linux-gnu/qtchooser/qt5.conf `and the file contain this:

`/usr/lib/qt5/bin`
`/usr/lib/x86_64-linux-gnu`

Check `qtchooser -l`:

```
qtchooser -l
4
5
default
qt4-x86_64-linux-gnu
qt4
qt5-x86_64-linux-gnu
qt5
```

Whatever option I choose with `qmake -qt `doesn't work.

**Comment by trytip** [comment]
install these should work after with qmake
`apt install libqt5charts5 libqt5charts5-dev`

**Comment by bkdwt** [comment]
> install these should work after with qmake
> `apt install libqt5charts5 libqt5charts5-dev`

Thanks! Works. ;)

**Comment by mikelward** [comment]
Could you update https://github.com/marazmista/radeon-profile/blob/master/README.md to reflect this please?

**Comment by marazmista** [comment]
@mikelward Updated (34cef06d0643c77d79239c304624417fc5036911)
