### ISSUE TITLE
Fan control not working for Radeon HD 6970 (using r600 driver)

### ISSUE THREAD

**Issue by bernandosoares** [marazmista/radeon-profile#17]
The fan control tab is completely grayed out, even when radeon-profile is run as root. Is this because of lack of support in the driver, or in radeon-profile?

**Comment by Danysan1** [comment]
Are all optional dependencies listed in https://github.com/marazmista/radeon-profile/blob/master/README.md installed?

**Comment by bernandosoares** [comment]
Yep

**Comment by bernandosoares** [comment]
I am running an up to date Manjaro system, if that helps

**Comment by marazmista** [comment]
According to news https://www.phoronix.com/scan.php?page=news_item&px=MTg0NDM (I haven't found anything newer) only cards HD7000 and above have fan support in the driver. To be sure, you can check if files, like `/sys/class/drm/card0/device/hwmon/hwmon2/pwm1` (card index may be different) and such exists in your system.
