### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by hydrian** [marazmista/radeon-profile#178]
Is there a CLI interface for switching profiles? I'd like to script profile changes depending on what I'm doing. This way i don't have to hear the GPU fan hum all the time.

**Comment by sinisa94** [comment]
Read documetation

**Comment by hydrian** [comment]
What documentation? All I see is https://github.com/marazmista/radeon-profile/blob/master/README.md and that talks nothing about CLI arguments. Is there someplace else the documentation is hiding and I'm not find it.

**Comment by marazmista** [comment]
No, I don't have plans regarding CLI interface, but puhsing values directly to sysfs files could be treated sort of like console interface.

**Comment by daroczig** [comment]
As far as I know, `sysfs` updates requires root-level access, while it would be much more convenient to rely on `radeon-profile-daemon` as a user -- if it's already running, so I still hope there's some chance for this in the future, although I understand it's not a priority.

**Comment by hydrian** [comment]
@daroczig Exactly. That's why I asked if radeon-profile had a CLI interface. Also, you can make a lot of changes with radeon-profile's profiles. Having a switch that could just switch from pre-saved profiles would be a great enhancement.

**Comment by hydrian** [comment]
Basically, I want to be able to set my fan curve profiles and performance mode when I start up a game automatically(read scripted) and revert it back once I'm done playing the game.
