### ISSUE TITLE
Configuration, Top Bar, Saving new settings Crash the program, Ubuntu 19.10 

### ISSUE THREAD

**Issue by JoneKone** [marazmista/radeon-profile#190]
Installed version from PPA 0.2.6+git43-7923bd6-201912051638~ubuntu19.10.1

After changes to the Top Bar I push save and it crashes the program, other-vice it seems to work fine.

**Comment by marazmista** [comment]
Confirmed. Seems like there is a problem with top bar items destructors.

**Comment by marazmista** [comment]
Fixed in commit: d17fb902779841a2a399e82c8dc5820800a964fe
