### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [marazmista/radeon-profile#191]
![Screenshot_2020-03-30_11-59-11](https://user-images.githubusercontent.com/564653/77934406-0c896c80-727e-11ea-8f13-cca9a8ce03dd.png)

Thanks for the great work you have done, by default this card get overvolted and this allows me to fix it and by unchecking the 300/1000 memory speeds i can OC and use dual monitors without artifacting

**Comment by marazmista** [comment]
Fixed in commit: 74009c7390afb98f3178c4f663e8c59df75fc2a1
