### ISSUE TITLE
Can't Switch between balanced and battery ASUS TUF 505DY

### ISSUE THREAD

**Issue by AnasR7** [marazmista/radeon-profile#197]
Hey this is so great to know this App.
Is working properly but I can't switch to balanced and battery, and in still in performance mode.

![amd](https://user-images.githubusercontent.com/23519166/80307031-deea0180-87f0-11ea-91a9-c41568d57505.gif)

And you can see is not support for asus fan maybe can you, patch it ?
[asus fanmode](https://github.com/leonmaxx/asus_fanmode)

Is wonderful if you can make it.
thanks

**Comment by marazmista** [comment]
>  Is working properly but I can't switch to balanced and battery, and in still in performance mode.

Fixed.
