### ISSUE TITLE
Failed to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by muzena** [marazmista/radeon-profile#210]
@marazmista 
Why is failed to build on Ubuntu 16.04?
Log file: https://launchpadlibrarian.net/482513065/buildlog_ubuntu-xenial-amd64.radeon-profile_20200504+git336-c50baac-202006021717~ubuntu16.04.1_BUILDING.txt.gz

**Comment by marazmista** [comment]
Probably kernel or libdrm is too old and it doesn't have defined `AMDGPU_INFO_SENSOR_STABLE_PSTATE_GFX_SCLK`.
