### ISSUE TITLE
Fan control custom curve is completely broken

### ISSUE THREAD

**Issue by olekolek1000** [marazmista/radeon-profile#211]
Yeah...
![curve](https://user-images.githubusercontent.com/29149078/84306342-a19cc180-ab5b-11ea-92ea-f6e2c3a4c81e.png)

**Comment by marazmista** [comment]
Fixed in commit: 83a379067ead6841ae1cd98dbc9bd0b0f37e113c. Please check if it is possible to get similar/same plot as shown on screenshot.

**Comment by olekolek1000** [comment]
Works perfectly now ;)
Thanks!
