### ISSUE TITLE
I can't change the "Set power profile to:" and "Set power level:" at event definition's window.

### ISSUE THREAD

**Issue by rizzini** [marazmista/radeon-profile#219]
When I click on those nothing appear. [Print](https://i.imgur.com/pw8Pyvy.jpg).

My intention is to always keep my GPU on low profile and back it up to normal only when a specified binary(e. g. Wine) is executed, but since I can't select any profile from the "Event definition", I can't find a way to do that. Is it even possible? It seems to be some very basic feature.

**Comment by marazmista** [comment]
Yes, that's the idea. You change event trigger to binary and choose from lists profiles that will be applied when you start binary. Are those lists empty (apart from 'No change' item)?
Please take a look at my response here: https://github.com/marazmista/radeon-profile/issues/218#issuecomment-659503026
Do you see buttons like those on the screenshot?

**Comment by rizzini** [comment]
> Yes, that's the idea.
I figured, but since nothing appears on those field, I started to question myself about if it's possible or if I am missing something.

> Do you see buttons like those on the screenshot?

No. I don't. Weird.

I have a RX580 8GB.
OS: Arch Linux

Thanks for the reply.

**Comment by marazmista** [comment]
#218 has been resolved and lists in Event definition should also work now. Please try build latest commit.

**Comment by megatog615** [comment]
This does not appear to work anymore. I can set Power Profile and Fan but I cannot change Power Level. I am also using an RX580. The buttons appear in the main window, and I can change settings freely. I just don't see power level options for events.
![Screenshot_20220304_143627](https://user-images.githubusercontent.com/3255620/156830341-b94bdd69-1378-4b4b-893f-161fbb6b8196.png)
