### ISSUE TITLE
Failed to build on Linux Mint 20

### ISSUE THREAD

**Issue by some-username-here1** [marazmista/radeon-profile#220]
After running `qmake`, then `make`, I get an error and a warning with the build failing to compile, the output being:
```
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG_OUTPUT -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCharts -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o dxorg.o dxorg.cpp
dxorg.cpp: In member function ‘GPUClocks dXorg::getClocksFromPmFile()’:
dxorg.cpp:198:12: warning: enumeration value ‘PP_MODE’ not handled in switch [-Wswitch]
  198 |     switch (features.currentPowerMethod) {
      |            ^
dxorg.cpp: In member function ‘PowerProfiles dXorg::getPowerProfiles(PowerMethod)’:
dxorg.cpp:885:65: error: ‘SkipEmptyParts’ is not a member of ‘Qt’
  885 |                 QStringList profileLine = sl[i].split(" " , Qt::SkipEmptyParts);
      |                                                                 ^~~~~~~~~~~~~~
make: *** [Makefile:714: dxorg.o] Error 1
```
Even though all of the dependencies mentioned in Readme are fulfilled.

**Comment by marazmista** [comment]
Yeah, so Qt has deprecated `QString::SkipEmptyParts` and advise to use `Qt::SkipEmptyParts` and QtCreator is flooded with messages:
![Przechwycenie obrazu ekranu_2020-07-17_23-00-02](https://user-images.githubusercontent.com/1813145/87830506-b19d7480-c870-11ea-9b99-1268eaab9628.png)
but then it is impossible to compile. I modifed this in commit: https://github.com/marazmista/radeon-profile/commit/9d3ef6c39b23b685532ae9c15c4ad53da6eaeaae so it should work.
Just curious, what version of Qt do you have installed?

**Comment by some-username-here1** [comment]
How do I check which version of Qt I have installed?

**Comment by marazmista** [comment]
In package manager, I think it is `qt5-defaults` package.. But you can also just type `qmake --version` and it should display what Qt version does it use.

**Comment by some-username-here1** [comment]
Here's my output, by the way:
```
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```

**Comment by marazmista** [comment]
That's pretty old. Current is 5.15.
If compilation works you can close the issue.

**Comment by some-username-here1** [comment]
It works now, thanks a bunch!
