### ISSUE TITLE
Ubuntu PPA failed to build

### ISSUE THREAD

**Issue by muzena** [marazmista/radeon-profile#222]
@marazmista 
Why failing to build in [Ubuntu 18.04.1, 20.04.1, 19.10.1](https://code.launchpad.net/~radeon-profile/+recipe/radeon-profile-git)?
[Ubuntu 18.04.1 build log](https://launchpadlibrarian.net/489027485/buildlog_ubuntu-bionic-amd64.radeon-profile_20200504+git354-673f1cd~ubuntu18.04.1_BUILDING.txt.gz)

**Comment by marazmista** [comment]
See here: https://github.com/marazmista/radeon-profile/issues/220#issuecomment-660337879
But this has been fixed and latest master should compile.
