### ISSUE TITLE
Switching between multiple cards adds profile buttons

### ISSUE THREAD

**Issue by amonforstmann** [marazmista/radeon-profile#230]
Switching between multiple cards adds profile buttons instead of replacing them

![image](https://user-images.githubusercontent.com/1593803/91912036-9072d500-ecb2-11ea-9485-c367b2d16abc.png)

```
QLayout: Attempting to add QLayout "" to QWidget "widget_pmControls", which already has a layout
QWidget::setLayout: Attempting to set QLayout "" on QWidget "widget_pmControls", which already has a layout
```

**Comment by marazmista** [comment]
I pushed a commit (1f98740b95b1de390d981f7894b93c5b46a44518) that should fix this, can you try now?

**Comment by amonforstmann** [comment]
@marazmista Thanks! I will close this issue.
