### ISSUE TITLE
Something wrong with graph tab

### ISSUE THREAD

**Issue by baryluk** [marazmista/radeon-profile#235]
Hi,

I just built the radeon-profile for the first time (I learned about it randomly from some random screenshot in ROCm issue thread).

Anyhow this is issue:

Running at 1f98740b95b1de390d981f7894b93c5b46a44518

Running as root

This is the graph tab:

![Screenshot at 2020-10-05 19-20-09](https://user-images.githubusercontent.com/110322/95122390-f6ce9580-073f-11eb-844e-67ed3074a3c0.png)

![Screenshot at 2020-10-05 19-21-48](https://user-images.githubusercontent.com/110322/95122453-0fd74680-0740-11eb-821c-c67271c6fd51.png)

![Screenshot at 2020-10-05 19-21-15](https://user-images.githubusercontent.com/110322/95122386-f59d6880-073f-11eb-9e88-a2507caf6dca.png)

That doesn't look right.

I am using Linux 5.7.6, with AMD Radeon R9 Fury X and `amdgpu.ppfeaturemask=0xffffffff`. I am vanilla amdgpu from upstream (I do have ROCm, but without rocm-dkms).

Most of the other tabs and values all look good, even fan control works.

**Comment by marazmista** [comment]
I think some default plots should show but anyway, when you click on Enable left scale or Enable right scale you should be able to choose which values you want for plots

**Comment by baryluk** [comment]
Indeed, it is possible to add new plots. It was a bit non intuitive. Maybe show instead all available data, always, and automatically enable left or right depending if anything is added. No need for the extra `Enable left scale`, `Enable right scale`.

![Screenshot at 2020-10-20 13-10-08](https://user-images.githubusercontent.com/110322/96590632-c78a5d80-12d5-11eb-9e49-5f013ad00529.png)


By default the "Graphs" shows no graphs for me. Kernel 5.7.6, Fury X, just like before.

**Comment by marazmista** [comment]
I checked with fresh configuration and indeed, there is no default plots. I pushed a commit where left scale is enabled by default when user create new plot (https://github.com/marazmista/radeon-profile/commit/0fd5b8dd326957e6fa8afda2bba5fc4c48fd0de4 ).

**Comment by baryluk** [comment]
@marazmista That is nice. It is now much more obvious what is going on.

I added few graphs, and they do look to work. The graph is kind of ugly, with no legend and all lines having same colour, but that is a topic for another time.
