### ISSUE TITLE
Cant "qmake" for some reasons.

### ISSUE THREAD

**Issue by ReShout876** [marazmista/radeon-profile#275]
Project MESSAGE: Building for release
Project ERROR: Unknown module(s) in QT: charts

I get this error. How do I fix this?
(Ubuntu 20.04.2 LTS x86_64)

**Comment by emerge-e-world** [comment]
You are missing the qt5 charts module. The package should be called `libqt5charts5-dev` in Ubuntu 20.04. Run:
`sudo apt-get install libqt5charts5-dev`

**Comment by Oxalin** [comment]
If this was fixed by installing the missing module, could you close the issue @ReShout876 

Otherwise, please add more details.
