### ISSUE TITLE
0% Fan Speed

### ISSUE THREAD

**Issue by tenten8401** [marazmista/radeon-profile#34]
Can we have the option for 0% fan speed? I have an XFX RX480 GTR that will go to 0% in idle.

**Comment by marazmista** [comment]
You can click Auto on fan control tab and then card decide itself if it should go to 0% when idle.

**Comment by Enigma0** [comment]
Auto is terrible though in every other respect. Ditto on wanting 0% fan speed functionality in the Custom Fan Curve.

**Comment by Danysan1** [comment]
Editing this line should be enough:
https://github.com/marazmista/radeon-profile/blob/master/radeon-profile/radeon_profile.h#L58

However I think that before we should implement some check  to prevent an user from frying its own card with an extreme fan profile...

**Comment by marazmista** [comment]
Ok, I will enable this in the future.

**Comment by marazmista** [comment]
Option added in commit dd35b94f6511c017424361e39be81e9045c82e1a
