### ISSUE TITLE
Hybrid Graphics setup

### ISSUE THREAD

**Issue by sanchitsamuel** [marazmista/radeon-profile#47]
I have a laptop with iGPU: Intel and dGPU: AMD
radeon-profile only detects the Intel card.
Even though I try running it on discrete GPU it still detects the iGPU only.

**Comment by marazmista** [comment]
It may be related to #46. Take a look here: https://github.com/marazmista/radeon-profile/issues/46#issuecomment-304142325

**Comment by marazmista** [comment]
Updates: https://github.com/marazmista/radeon-profile/issues/46#issuecomment-308267869

**Comment by marazmista** [comment]
Fixed by merge or `rp-dev`: ac594203b2b89001304d73c38bb3c87a4adbd4c8
