### ISSUE TITLE
When graphs are disabled, random value is displayed for current fan speed

### ISSUE THREAD

**Issue by ChristophHaag** [marazmista/radeon-profile#48]
Go to Configuration, disable the checkbox Update: "GPU data, power profile, temperature".

Restart radeon-profile. Observe a random value in the dropdownbox where the current fan speed should be displayed.

![radeon-profile-nographs](https://cloud.githubusercontent.com/assets/781076/24977327/f47769aa-1fcc-11e7-822f-e8da254d3a15.png)

**Comment by marazmista** [comment]
Fixed in commit 757fa511908d79c5fa5f078bac777ef4d8d3701f
