### ISSUE TITLE
No systemtrayicon available

### ISSUE THREAD

**Issue by DroWnThePoor** [marazmista/radeon-profile#49]
I'm on Elementary OS 0.4-Loki (Ubuntu 16.04 ) and I get No systemtrayicon available when I run this.
What is the best way to go about fixing this?

Very grateful to you for this program, by the way.

**Comment by Enigma0** [comment]
I think you need to build the daemon also.

**Comment by marazmista** [comment]
Looks like elementary doesn't support tray icons.
Can you try workaround described here? https://www.reddit.com/r/elementaryos/comments/525rmv/missing_system_tray_icons_loki/d7iydfk/
