### ISSUE TITLE
Missing dependency: libQtGui.so.4

### ISSUE THREAD

**Issue by Enigma0** [marazmista/radeon-profile#51]
~$ radeon-profile: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory

**Comment by marazmista** [comment]
Libraries were never distributed with radeon-profile. Maybe during update Qt package got corrupted? Or maybe you have radeon-profile compiled for Qt4 and in system you have only Qt5 libs?

**Comment by Enigma0** [comment]
Maybe? While I get that packages aren't distributed here, a general list of packages one would need to install/have installed would be nice to have in the project description.

**Comment by marazmista** [comment]
Modified list of dependencies in readme: https://github.com/marazmista/radeon-profile#dependencies
