### ISSUE TITLE
Optionally read the GPU load from amdgpu_pm_info

### ISSUE THREAD

**Issue by higuita** [marazmista/radeon-profile#57]
amdgpu_pm_info have the GPU load, it would be good if one could read and graph that info too.

in another ticket, it is referred that it cause small delays, but to help debug performance issued, it is useful, so it should be disabled by default, and user get a warning if enabled.

Thanks for the tool!

**Comment by marazmista** [comment]
Already done in `rp-dev` branch https://github.com/marazmista/radeon-profile/tree/rp-dev

**Comment by marazmista** [comment]
Merged: ac594203b2b89001304d73c38bb3c87a4adbd4c8

**Comment by higuita** [comment]
I tried the latest version and my GPU still reports 0% load, yet the amdgpu_pm_info reports load without any problem

**Comment by marazmista** [comment]
Do you get `Invalid argument` messages in output when you run it in terminal?

**Comment by higuita** [comment]
No, this is my output:

```
# radeon-profile
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
```
the GPU always show 0
when closing, this extra message show up:
```
context mis-match in pipe_sampler_view_release()
```

running with radeon-profile-daemon and running as a user, i get the same result

**Comment by higuita** [comment]
just to update: i updated to the latest version and still the same problem, no gpu load show up

**Comment by Scoopta** [comment]
Using the latest version with an R9 Fury running mesa and amdgpu and I can confirm that I also have 0% load.

**Comment by marazmista** [comment]
What is your kernel version?

**Comment by Scoopta** [comment]
4.12.4

**Comment by lhorace** [comment]
@higuita Was this issue resolved for you? It's been closed without any indication is working for you?

**Comment by higuita** [comment]
Sorry, no, this is not solved

using the latest radeon-profile, both with and without radeon-profile-daemon, on a update system:

OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (AMD POLARIS10 / DRM 3.18.0 / 4.13.0-slack, LLVM 4.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.0
my libdrm is 2.4.83

**Comment by Enigma0** [comment]
Same issue:

![no_gpu_usage](https://user-images.githubusercontent.com/4528283/31063688-4c62af22-a703-11e7-86c1-734334778d0a.png)
