### ISSUE TITLE
Add underclock feature

### ISSUE THREAD

**Issue by Supatier** [marazmista/radeon-profile#60]
Hi
I'm using RX 480 8Gb with a moded bios to RX 580 and it's unstable  when gaming on high settings.
An underclock feature would be really usefull.
Cheers

**Comment by marazmista** [comment]
In 20170703 I added manual frequency control, so you can use this to set lower clocks frequency.

**Comment by Supatier** [comment]
It works but, i need a refined slider or maybe enter the  frequency number?

**Comment by marazmista** [comment]
It's slider. Kernel support only defined frequencies.

**Comment by Supatier** [comment]
Well then...
