### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: charts (Ubuntu 17.04)

### ISSUE THREAD

**Issue by Enigma0** [marazmista/radeon-profile#66]
Ubuntu 17.04 seems to not have `libqt5charts5*.deb`

README should probably mention:

* http://launchpadlibrarian.net/316647367/libqt5charts5_5.7.1-3_amd64.deb
* http://launchpadlibrarian.net/316647362/libqt5charts5-dev_5.7.1-3_amd64.deb

Even having installed those, I still see the above error when building.

**Comment by marazmista** [comment]
Looks like this may be related: https://bugs.launchpad.net/ubuntu/+source/qtcharts-opensource-src/+bug/1682643
Can you try install qtcharts-opensource-src as noted in link? Maybe this will help.

**Comment by Enigma0** [comment]
@marazmista I did see that. That's where I found the .debs that seemed relevant. Not sure how to install that as a whole - it looks like it just has a lot of .deb's

I also just installed http://launchpadlibrarian.net/316647368/qml-module-qtcharts_5.7.1-3_amd64.deb but still same error.

As per https://launchpad.net/ubuntu/+source/qtcharts-opensource-src/5.7.1-3/+build/12462945 the only packages I didn't install are the -dbgsym, docs & example ones.

**Comment by marazmista** [comment]
Can you check if you have QtCharts directory in `/usr/include/qt`?

**Comment by Enigma0** [comment]
@marazmista Not entirely sure what's going on here but this is all I have:

```
:/usr/include$ ls -l | grep qt
drwxr-xr-x 19 root root   4096 Jul 13 12:43 qt4
drwxr-xr-x  3 root root   4096 Jul 18 20:05 qt4qevercloud
drwxr-xr-x  2 root root   4096 Jul 18 19:50 qt5keychain
drwxr-xr-x  3 root root   4096 Jul 18 19:50 qt5qevercloud
```

**Comment by Enigma0** [comment]
@marazmista I reinstalled GNOME 17.04 and I have nothing in `/usr/include`.

What am I supposed to install?

I have this but how do I use it? Some instructions in the README would be useful.

```
:/opt/Qt5.9.1/5.9.1/gcc_64/include$ ls -l | grep Chart
drwxrwxr-x 3 root root  4096 Jul 31 01:23 QtCharts
```

**Comment by Enigma0** [comment]
Issue is resolved for me following the updated README in pull request: https://github.com/marazmista/radeon-profile/pull/65#pullrequestreview-54519918

**Comment by MasterCATZ** [comment]
Ubuntu 17.10

sudo apt install libqt5charts5 libqt5charts5-dev

worked for me 

libqt5charts5 is already the newest version (5.9.1-3).
libqt5charts5-dev is already the newest version (5.9.1-3).

**Comment by Enigma0** [comment]
That's awesome. Must have just been an oversight with `17.04`.

**Comment by MishkaRogachev** [comment]
sudo apt install qml-module-qtcharts
