### ISSUE TITLE
Core or Memory clock options are not showing in the applications

### ISSUE THREAD

**Issue by lhorace** [marazmista/radeon-profile#73]
Hi,

**OS:** ArchLinux 
**Kernel:** 4.12.8-1-zen
**GPU:** XFX RX 480

Reading issue #54, AMDGPU clock info is available for Kernels >= 4.12? However that information is missing and not selectable in Radeon Profile 20170714 with Radeon Daemon enabled and running. The code in rp-dev branch is not merged with the main branch yet?

**Comment by marazmista** [comment]
This info should be visible if you don't have 'Use daemon as data provider' checked in config.
rp-dev was merged and master is most recent now.

**Comment by lhorace** [comment]
Ahh, okay, thanks!!!!!!!!!!!
