### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by marathone** [marazmista/radeon-profile#84]
Ubuntu-Bugs was invoked on segfault on startup. I had to take several screengrabs to capture the entire data.

Attached for your convenience.

![screenshot-20180108084951-1023x369](https://user-images.githubusercontent.com/21069165/34674404-c4990fc0-f453-11e7-94be-243f2344294c.png)
![screenshot-20180108084922-1130x1034](https://user-images.githubusercontent.com/21069165/34674405-c4bbb6ec-f453-11e7-9e2f-478099a730a4.png)
![screenshot-20180108084846-1130x1034](https://user-images.githubusercontent.com/21069165/34674406-c4d9d2e4-f453-11e7-8fe7-d93c62c2b15f.png)
![screenshot-20180108084814-1130x1034](https://user-images.githubusercontent.com/21069165/34674407-c4fd5b06-f453-11e7-882d-d9cade1a92fc.png)

**Comment by marazmista** [comment]
QTimer is mentioned in screenshots, maybe it is related to #75 which is fixed by f9f496f7dff8ef747937c00409c23f5473c17de3 commit.
