### ISSUE TITLE
Changes in fan control profiles are not saved

### ISSUE THREAD

**Issue by sr258** [marazmista/radeon-profile#87]
When I change a profile in the tab "Fan Controls" and hit the "Save" button, the changes are applied and the fans spin as they are supposed to. After a reboot, the changes are lost however and the profile is like it used to be before the change.

EDIT:
The changes are actually saved if you manually quit the program. If the program is terminated because you reboot, the changes are lost.

**Comment by marazmista** [comment]
Fixed in commit: 75391522b287ddfb1d1fb5793daee64aa7bf163d
