### ISSUE TITLE
I can't execute the program, it doesn't appear to install on /usr/bin

### ISSUE THREAD

**Issue by estkma** [marazmista/radeon-profile#90]
As the title says, it doesn't seems to install on my /usr/bin folder, it seems to compile well i didn't notice something rare on the process. I'm using Debian Testing.

**Comment by blisbell** [comment]
You have to manually install unless installing from a repo or ppa. It can only be compiled from git.

**Comment by estkma** [comment]
Thanks for the reply man, i will do that.
