### ISSUE TITLE
Core or Memory Clock manual options grayed out with "use daemon as data provider" unchecked

### ISSUE THREAD

**Issue by xxmodxx788** [marazmista/radeon-profile#91]
I am somewhat new to linux to hi o/.
OS: Ubuntu 18.04
GPU: XFX R7 240 2gb
I tried the issue with the same problem already but I already have it Unchecked in the screenshots below. Any idea? (daemon ran as sudo) (radeon profile not ran as sudo)
![screenshot from 2018-07-26 08-34-01](https://user-images.githubusercontent.com/7832112/43262599-b802f120-90ae-11e8-9f92-f49003b36f25.png)
![screenshot from 2018-07-26 08-34-08](https://user-images.githubusercontent.com/7832112/43262600-b81125b0-90ae-11e8-8214-567edcaf77d7.png)

**Comment by marazmista** [comment]
Manual frequency control is not related to 'use daemon as data provider' setting.
Check if you have `/sys/class/drm/card0/device/pp_dpm_sclk` file because it it used to set frequency manually.

**Comment by marazmista** [comment]
Implemented in 9a364be47b751165504362b49b38d011c6712636 and e7922095c2cea1de4f8cee61441496891ddb0bd7
